(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const sectors=[
 {id:'earth',short:'EARTH',name:'วงโคจรโลก',dataGoal:6,killGoal:5,desc:'ฝ่าเขตดาวเทียม เก็บ Data Core และรับมือหน่วยสอดแนมเอเลี่ยน',bg:['#061329','#102d62'],questions:[['แรงหลักที่ทำให้ดาวเทียมโคจรรอบโลกคืออะไร?',['แรงโน้มถ่วง','แรงลม','แรงเสียง','แรงแม่เหล็ก'],0],['สถานีอวกาศนานาชาติอยู่บริเวณใด?',['วงโคจรต่ำของโลก','พื้นผิวดวงจันทร์','ดาวอังคาร','นอกกาแล็กซี'],0]]},
 {id:'moon',short:'MOON',name:'เส้นทางดวงจันทร์',dataGoal:7,killGoal:7,desc:'เร่งออกจากโลก หลบอุกกาบาต และสู้กับฝูง Saucer ระหว่างทาง',bg:['#090d1f','#303751'],questions:[['แสงที่เราเห็นจากดวงจันทร์ส่วนใหญ่คืออะไร?',['แสงอาทิตย์สะท้อนพื้นผิว','แสงที่ดวงจันทร์สร้างเอง','แสงจากโลกเท่านั้น','แสงจากดาวอังคาร'],0],['แรงโน้มถ่วงบนดวงจันทร์เมื่อเทียบกับโลกเป็นอย่างไร?',['น้อยกว่าโลก','มากกว่าโลก','เท่ากัน','ไม่มีแรงโน้มถ่วง'],0]]},
 {id:'mars',short:'MARS',name:'แนวรบดาวอังคาร',dataGoal:8,killGoal:9,desc:'ฝ่าพายุฝุ่น เก็บเทคโนโลยี และรับมือยานเอเลี่ยนติดอาวุธหนัก',bg:['#190a08','#71301f'],questions:[['ทำไมดาวอังคารจึงมีสีแดง?',['เหล็กออกไซด์บนพื้นผิว','มหาสมุทรสีแดง','แสงจากดาวพฤหัสบดี','มีไฟลุกตลอดเวลา'],0],['ดาวอังคารเป็นดาวเคราะห์ลำดับที่เท่าไรจากดวงอาทิตย์?',['4','2','6','8'],0]]},
 {id:'hole',short:'BLACK HOLE',name:'สมรภูมิขอบหลุมดำ',dataGoal:10,killGoal:12,desc:'แรงโน้มถ่วงปั่นป่วน ศัตรูเร็วขึ้น และมี Alien Commander รออยู่',bg:['#080511','#2b1640'],questions:[['ขอบเขตที่ผ่านแล้วแม้แต่แสงก็กลับออกมาไม่ได้เรียกว่าอะไร?',['Event Horizon','Solar Ring','Gravity Wall','Photon Sea'],0],['แรงใดเด่นที่สุดใกล้หลุมดำ?',['แรงโน้มถ่วง','แรงลม','แรงเสียดทานอากาศ','แรงลอยตัว'],0]]}
];
const ships=[
 {id:'comet',name:'COMET-01',icon:'🚀',desc:'สมดุล คล่องตัว ยิงเร็ว เหมาะสำหรับผู้เล่นครั้งแรก',speed:78,armor:76,fire:78,move:1,damage:1},
 {id:'sting',name:'STING-R',icon:'🛩️',desc:'เร็วมากและเร่งไว แต่ Hull บางกว่า เหมาะกับสายหลบยิง',speed:96,armor:52,fire:88,move:1.28,damage:1.18},
 {id:'tank',name:'NOVA-T',icon:'🛸',desc:'ยานหนัก Hull สูง กระสุนแรง แต่เลี้ยวช้ากว่า',speed:62,armor:98,fire:62,move:.85,damage:.72}
];
const weapons={pulse:{name:'PULSE CANNON',desc:'ยิงตรง ความเร็วสูง',rate:.22},rapid:{name:'RAPID BLASTER',desc:'ยิงรัวต่อเนื่อง',rate:.105},spread:{name:'TRI-SHOT',desc:'ยิงกระจาย 3 ทิศ',rate:.24},plasma:{name:'PLASMA BALL',desc:'กระสุนใหญ่ทะลุศัตรู',rate:.38}};
const diff={easy:{enemy:.82,spawn:1.22,damage:.72},normal:{enemy:1,spawn:1,damage:1},hard:{enemy:1.2,spawn:.8,damage:1.25}};
const state={screen:'home',ship:0,sector:0,score:0,data:0,kills:0,totalKills:0,sectors:0,fuel:100,hull:100,rescues:0,combo:1,bestCombo:1,comboT:0,running:false,paused:false,boost:false,reverse:false,fire:false,keys:{left:false,right:false,up:false,down:false},weapon:'pulse',weaponLevel:1,weaponT:0,shieldT:0,magnetT:0,droneT:0,stars:[],bullets:[],enemyBullets:[],enemies:[],cores:[],pickups:[],particles:[],enemySpawn:1,coreSpawn:1,pickupCount:0,waveT:7,waveActive:0,last:0,raf:0,fireT:0,idle:null,audio:null,settings:{difficulty:'normal',volume:70,idle:60,sound:true},rescueType:'hull',qIndex:0};
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),arena=$('#arena');
let W=1,H=1,DPR=1;
const player={x:0,y:0,vx:0,vy:0,w:48,h:58,inv:0};
function loadSettings(){try{Object.assign(state.settings,JSON.parse(localStorage.getItem('cosmic.v4.settings')||'{}'))}catch(_){} $('#difficultySelect').value=state.settings.difficulty;$('#volumeRange').value=state.settings.volume;$('#volumeValue').textContent=state.settings.volume+'%';$('#idleRange').value=state.settings.idle;$('#idleValue').textContent=state.settings.idle+'s';updateSound()}
function leaders(){try{return JSON.parse(localStorage.getItem('cosmic.v4.leaders')||'[]')}catch(_){return[]}}
function saveLeader(){const a=leaders();a.push({score:state.score,kills:state.totalKills,sectors:state.sectors,ship:ships[state.ship].name});a.sort((x,y)=>y.score-x.score);localStorage.setItem('cosmic.v4.leaders',JSON.stringify(a.slice(0,8)));renderLeaders()}
function renderLeaders(){const a=leaders(),box=$('#leaderboard');box.innerHTML=a.length?a.slice(0,5).map((x,i)=>`<div class="row"><b>#${i+1}</b><div>${x.ship}<small>${x.kills} aliens · ${x.sectors} sectors</small></div><strong>${x.score}</strong></div>`).join(''):'<p style="color:#a9b5d3;font-size:12px">ยังไม่มีคะแนน</p>'}
function renderHome(){const icons=['🌍','🌕','🔴','🕳️'];$('#routePreview').innerHTML=sectors.map((s,i)=>`<div>${icons[i]}<b>${s.short}</b><small>${s.dataGoal} data · ${s.killGoal} alien</small></div>`).join('');renderLeaders()}
function renderShips(){const box=$('#shipCards');box.innerHTML='';ships.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.className='ship-card'+(i===state.ship?' selected':'');b.innerHTML=`<div class="ship-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.desc}</p><div class="stats"><div><span>SPEED</span><i><span style="width:${s.speed}%"></span></i><b>${s.speed}</b></div><div><span>ARMOR</span><i><span style="width:${s.armor}%"></span></i><b>${s.armor}</b></div><div><span>FIRE</span><i><span style="width:${s.fire}%"></span></i><b>${s.fire}</b></div></div>`;b.addEventListener('click',()=>{state.ship=i;renderShips();sfx('tap')});box.appendChild(b)})}
function show(name){state.screen=name;$$('.screen').forEach(x=>x.classList.toggle('active',x.id==='screen'+name[0].toUpperCase()+name.slice(1)));resetIdle()}
function resetRun(){Object.assign(state,{sector:0,score:0,data:0,kills:0,totalKills:0,sectors:0,fuel:100,hull:100,rescues:0,combo:1,bestCombo:1,comboT:0,weapon:'pulse',weaponLevel:1,weaponT:0,shieldT:0,magnetT:0,droneT:0,pickupCount:0});state.bullets=[];state.enemyBullets=[];state.enemies=[];state.cores=[];state.pickups=[];state.particles=[];updateHud()}
function setupRun(){resetRun();$('#briefOverlay').classList.remove('hidden');$('#briefTitle').textContent=sectors[0].name;$('#briefText').textContent=sectors[0].desc;$('#briefGoal').textContent=`เก็บ Data ${sectors[0].dataGoal} · ยิง Alien ${sectors[0].killGoal}`;show('game');resize();draw()}
async function countdown(){ensureAudio();$('#briefOverlay').classList.add('hidden');$('#countOverlay').classList.remove('hidden');for(const n of [3,2,1]){$('#countValue').textContent=n;sfx('count');await wait(550)}$('#countValue').textContent='GO!';sfx('go');await wait(350);$('#countOverlay').classList.add('hidden');startSector()}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function startSector(){state.running=true;state.paused=false;state.last=performance.now();state.enemySpawn=.6;state.coreSpawn=.6;state.waveT=6;state.waveActive=0;player.x=W/2;player.y=H*.72;player.vx=player.vy=0;player.inv=2;cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(loop);arena.focus();updateHud();sfx('launch')}
function profile(){return diff[state.settings.difficulty]||diff.normal}
function worldSpeed(){if(state.reverse)return .32;if(state.boost)return 1.75;return 1}
function update(dt){if(!state.running||state.paused)return;const sec=sectors[state.sector],sp=ships[state.ship],pf=profile(),ws=worldSpeed();
 const ax=((state.keys.right?1:0)-(state.keys.left?1:0))*980*sp.move,ay=((state.keys.down?1:0)-(state.keys.up?1:0))*900*sp.move;player.vx+=ax*dt;player.vy+=ay*dt;player.vx*=Math.pow(.006,dt);player.vy*=Math.pow(.006,dt);player.x+=player.vx*dt;player.y+=player.vy*dt;player.x=Math.max(28,Math.min(W-28,player.x));player.y=Math.max(40,Math.min(H-34,player.y));player.inv=Math.max(0,player.inv-dt);
 state.fuel-=((state.boost?3.6:state.reverse?.35:.82))*dt; if(state.fuel<=0){state.fuel=0;return triggerRescue('fuel')}
 state.comboT-=dt;if(state.comboT<=0){state.combo=1;state.comboT=0}state.weaponT=Math.max(0,state.weaponT-dt);if(state.weaponT<=0&&state.weapon!=='pulse'){state.weapon='pulse';state.weaponLevel=1}state.shieldT=Math.max(0,state.shieldT-dt);state.magnetT=Math.max(0,state.magnetT-dt);state.droneT=Math.max(0,state.droneT-dt);
 state.stars.forEach(s=>{s.y+=s.v*ws*dt;if(s.y>H+10){s.y=-5;s.x=Math.random()*W}});
 state.fireT-=dt;if(state.fire&&state.fireT<=0)fireWeapon();
 state.enemySpawn-=dt;if(state.enemySpawn<=0&&state.enemies.length<16){spawnEnemy();state.enemySpawn=(1.05+Math.random()*.75)*pf.spawn/(state.waveActive?1.8:1)}
 state.coreSpawn-=dt;if(state.coreSpawn<=0&&state.cores.length<10){state.cores.push({x:35+Math.random()*(W-70),y:-20,r:11,v:95+Math.random()*35,rot:0});state.coreSpawn=1.2+Math.random()*1.15}
 state.waveT-=dt;if(state.waveT<=0){startWave();state.waveT=13+Math.random()*8}state.waveActive=Math.max(0,state.waveActive-dt);
 if(state.droneT>0&&state.fireT<.05&&Math.random()<dt*4)spawnDroneBullet();
 updateBullets(dt,ws);updateEnemies(dt,pf,ws);updateObjects(dt,ws);updateParticles(dt);if(checkSector())completeSector();updateHud()}
function spawnEnemy(){const sec=state.sector,r=Math.random();let type='scout';if(sec>=1&&r>.55)type='zig';if(sec>=2&&r>.72)type='gun';if(sec>=3&&r>.88)type='saucer';const hp={scout:1,zig:2,gun:3,saucer:6}[type];state.enemies.push({type,x:35+Math.random()*(W-70),y:-40,vx:(Math.random()-.5)*60,vy:78+Math.random()*45+sec*12,hp,max:hp,phase:Math.random()*6.28,shot:.8+Math.random()*1.5,r:type==='saucer'?28:type==='gun'?23:19})}
function startWave(){state.waveActive=5;const labels=['SCOUT SWARM!','SAUCER ATTACK!','GUNSHIP WAVE!'];$('#waveTitle').textContent=labels[Math.min(state.sector,2)];$('#waveBanner').classList.remove('hidden');setTimeout(()=>$('#waveBanner').classList.add('hidden'),1500);for(let i=0;i<Math.min(5,16-state.enemies.length);i++)setTimeout(spawnEnemy,i*120);sfx('wave')}
function fireWeapon(){const w=weapons[state.weapon],rate=Math.max(.07,w.rate-(state.weaponLevel-1)*.025);state.fireT=rate;const base={x:player.x,y:player.y-28,vy:-560,vx:0,r:4,damage:1,pierce:state.weapon==='plasma'};if(state.weapon==='spread'){[-.22,0,.22].forEach(a=>state.bullets.push({...base,vx:Math.sin(a)*220,vy:-Math.cos(a)*540}))}else if(state.weapon==='plasma')state.bullets.push({...base,r:9,damage:2,vy:-440});else state.bullets.push(base);if(state.bullets.length>80)state.bullets.splice(0,state.bullets.length-80);sfx('shoot')}
function spawnDroneBullet(){if(!state.enemies.length)return;const target=state.enemies.reduce((a,b)=>b.y>a.y?b:a,state.enemies[0]),dx=target.x-player.x,dy=target.y-player.y,len=Math.max(1,Math.hypot(dx,dy));state.bullets.push({x:player.x+24,y:player.y,vx:dx/len*430,vy:dy/len*430,r:3,damage:1,pierce:false,drone:true})}
function updateBullets(dt,ws){state.bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});state.enemyBullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt*ws});for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i];let hit=false;for(let j=state.enemies.length-1;j>=0;j--){const e=state.enemies[j];if(dist(b,e)<b.r+e.r){e.hp-=b.damage;burst(b.x,b.y,'hit',5);hit=true;if(e.hp<=0)destroyEnemy(j,e);if(!b.pierce)break}}if(hit&&!b.pierce)state.bullets.splice(i,1);else if(b.y<-40||b.y>H+40||b.x<-40||b.x>W+40)state.bullets.splice(i,1)}
 for(let i=state.enemyBullets.length-1;i>=0;i--){const b=state.enemyBullets[i];if(dist(b,player)<b.r+20){state.enemyBullets.splice(i,1);damagePlayer(10+state.sector*2);continue}if(b.y>H+30||b.x<-30||b.x>W+30)state.enemyBullets.splice(i,1)}if(state.enemyBullets.length>50)state.enemyBullets.splice(0,state.enemyBullets.length-50)}
function updateEnemies(dt,pf,ws){for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];e.phase+=dt*2.3;const sway=e.type==='zig'?Math.sin(e.phase)*130:e.type==='saucer'?Math.sin(e.phase*.7)*80:0;e.x+=((e.vx+sway)*dt);e.y+=e.vy*pf.enemy*ws*dt;e.x=Math.max(e.r,Math.min(W-e.r,e.x));e.shot-=dt;if((e.type==='gun'||e.type==='saucer'||(e.type==='zig'&&state.sector>=2))&&e.shot<=0&&e.y>30&&e.y<H*.65){shootEnemy(e);e.shot=e.type==='saucer'?.65:1.2+Math.random()*.7}if(dist(e,player)<e.r+24){state.enemies.splice(i,1);damagePlayer(e.type==='saucer'?32:20);burst(e.x,e.y,'boom',18);continue}if(e.y>H+60)state.enemies.splice(i,1)}}
function shootEnemy(e){const dx=player.x-e.x,dy=player.y-e.y,len=Math.max(1,Math.hypot(dx,dy)),spd=e.type==='saucer'?260:210;state.enemyBullets.push({x:e.x,y:e.y+15,vx:dx/len*spd,vy:dy/len*spd,r:e.type==='saucer'?6:4});sfx('enemy')}
function updateObjects(dt,ws){state.cores.forEach(c=>{c.y+=c.v*ws*dt;c.rot+=dt*2.6});state.pickups.forEach(p=>{p.y+=p.v*ws*dt;p.rot+=dt*2});if(state.magnetT>0){[...state.cores,...state.pickups].forEach(o=>{const dx=player.x-o.x,dy=player.y-o.y,l=Math.hypot(dx,dy);if(l<260&&l>1){o.x+=dx/l*280*dt;o.y+=dy/l*280*dt}})}for(let i=state.cores.length-1;i>=0;i--){const c=state.cores[i];if(dist(c,player)<c.r+24){state.cores.splice(i,1);state.data++;combo();addScore(80);burst(c.x,c.y,'data',12);state.fuel=Math.min(100,state.fuel+2);sfx('collect')}else if(c.y>H+30)state.cores.splice(i,1)}for(let i=state.pickups.length-1;i>=0;i--){const p=state.pickups[i];if(dist(p,player)<p.r+24){state.pickups.splice(i,1);applyPickup(p.type);burst(p.x,p.y,p.type,14)}else if(p.y>H+30)state.pickups.splice(i,1)}}
function destroyEnemy(i,e){state.enemies.splice(i,1);state.kills++;state.totalKills++;combo();addScore(e.type==='saucer'?260:e.type==='gun'?160:100);burst(e.x,e.y,'boom',18);sfx('boom');if(Math.random()<.34&&state.pickups.length<8)dropPickup(e.x,e.y)}
function dropPickup(x,y){const pool=['fuel','repair','rapid','spread','plasma','shield','magnet','drone'];const type=pool[Math.floor(Math.random()*pool.length)];state.pickups.push({type,x,y,r:13,v:85,rot:0})}
function applyPickup(type){state.pickupCount++;combo();addScore(70);const map={fuel:'⚡ FUEL +25',repair:'🔧 REPAIR +25',rapid:'🔫 RAPID BLASTER',spread:'🔱 TRI-SHOT',plasma:'🟣 PLASMA BALL',shield:'🛡️ SHIELD 7s',magnet:'🧲 MAGNET 8s',drone:'🤖 DRONE WINGMAN'};if(type==='fuel')state.fuel=Math.min(100,state.fuel+25);else if(type==='repair')state.hull=Math.min(100,state.hull+25);else if(['rapid','spread','plasma'].includes(type)){state.weapon=type;state.weaponLevel=Math.min(3,state.weaponLevel+1);state.weaponT=14}else if(type==='shield')state.shieldT=7;else if(type==='magnet')state.magnetT=8;else if(type==='drone')state.droneT=12;showPickup(map[type]);sfx('power')}
function damagePlayer(amount){if(player.inv>0||state.shieldT>0)return;state.hull-=amount*ships[state.ship].damage*profile().damage;player.inv=.7;state.combo=1;state.comboT=0;arena.classList.remove('shake');void arena.offsetWidth;arena.classList.add('shake');$('#damageFlash').classList.remove('on');void $('#damageFlash').offsetWidth;$('#damageFlash').classList.add('on');sfx('hit');if(state.hull<=0){state.hull=0;triggerRescue('hull')}}
function combo(){if(state.comboT>0)state.combo=Math.min(6,state.combo+1);else state.combo=1;state.comboT=3.5;state.bestCombo=Math.max(state.bestCombo,state.combo)}function addScore(n){state.score+=Math.round(n*state.combo)}
function checkSector(){const s=sectors[state.sector];return state.data>=s.dataGoal&&state.kills>=s.killGoal}
async function completeSector(){state.running=false;cancelAnimationFrame(state.raf);state.sectors++;state.score+=600;sfx('clear');if(state.sector>=sectors.length-1){return finishRun(true)}const from=sectors[state.sector],to=sectors[state.sector+1];$('#sectorTitle').textContent=to.name;$('#sectorSub').textContent=`${from.short} → ${to.short} · เติมทรัพยากรระหว่าง Warp`;$('#sectorOverlay').classList.remove('hidden');state.fuel=Math.min(100,state.fuel+25);state.hull=Math.min(100,state.hull+20);await wait(1500);state.sector++;state.data=0;state.kills=0;state.enemies=[];state.enemyBullets=[];state.cores=[];state.pickups=[];$('#sectorOverlay').classList.add('hidden');startSector()}
function triggerRescue(type){if(state.paused)return;state.paused=true;state.running=false;cancelAnimationFrame(state.raf);state.rescueType=type;state.qIndex=(state.qIndex+1)%sectors[state.sector].questions.length;$('#rescueIcon').textContent=type==='fuel'?'⚡':'🔧';$('#rescueTitle').textContent=type==='fuel'?'ENERGY EMPTY!':'HULL CRITICAL!';$('#rescueText').textContent=type==='fuel'?'ตอบถูกเพื่อเติม Energy 65% แล้วบินต่อ':'ตอบถูกเพื่อซ่อม Hull 70% แล้วกลับไปสู้ต่อ';$('#rescueOverlay').classList.remove('hidden');renderQuestion();sfx('alarm')}
function renderQuestion(){const [q,a,c]=sectors[state.sector].questions[state.qIndex];$('#rescueQuestion').textContent=q;$('#rescueFeedback').textContent='';const box=$('#rescueAnswers');box.innerHTML='';a.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.textContent=x;b.addEventListener('click',()=>answerQuestion(i,c,b));box.appendChild(b)})}
function answerQuestion(i,c,btn){const bs=$$('#rescueAnswers button');bs.forEach(b=>b.disabled=true);bs[c]?.classList.add('correct');if(i===c){state.rescues++;state.score+=200;if(state.rescueType==='fuel')state.fuel=65;else state.hull=70;$('#rescueFeedback').textContent='✓ ถูกต้อง! ระบบกู้ยานทำงาน';sfx('rescue');setTimeout(()=>{$('#rescueOverlay').classList.add('hidden');state.paused=false;state.running=true;player.inv=2.5;state.last=performance.now();state.raf=requestAnimationFrame(loop)},900)}else{btn.classList.add('wrong');state.score=Math.max(0,state.score-50);$('#rescueFeedback').textContent='ยังไม่ถูก เปลี่ยนคำถามแล้วลองใหม่';sfx('fail');setTimeout(()=>{state.qIndex=(state.qIndex+1)%sectors[state.sector].questions.length;renderQuestion()},800)}}
function finishRun(success=false){state.running=false;cancelAnimationFrame(state.raf);saveLeader();show('report');$('#reportTitle').textContent=success?'GALAXY CLEARED!':'EXPEDITION REPORT';$('#reportScore').textContent=state.score.toLocaleString('th-TH');$('#reportSectors').textContent=state.sectors;$('#reportKills').textContent=state.totalKills;$('#reportRescues').textContent=state.rescues;$('#reportCombo').textContent='x'+state.bestCombo;$('#reportPowers').textContent=state.pickupCount;sfx('clear')}
function showPickup(t){const e=$('#pickupToast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1200)}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function burst(x,y,type,n){for(let i=0;i<n;i++)state.particles.push({x,y,vx:(Math.random()-.5)*280,vy:(Math.random()-.5)*280,life:.45+Math.random()*.45,max:.9,r:1+Math.random()*4,type});if(state.particles.length>120)state.particles.splice(0,state.particles.length-120)}
function updateParticles(dt){state.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy*=.98;p.life-=dt});state.particles=state.particles.filter(p=>p.life>0)}
function loop(t){if(!state.running)return;const dt=Math.min(.033,(t-state.last)/1000||0);state.last=t;update(dt);draw();if(state.running)state.raf=requestAnimationFrame(loop)}
function resize(){const r=arena.getBoundingClientRect();DPR=Math.min(devicePixelRatio||1,2);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);state.stars=Array.from({length:Math.min(150,Math.max(90,Math.floor(W*H/5200)))},()=>({x:Math.random()*W,y:Math.random()*H,v:25+Math.random()*95,s:.5+Math.random()*1.8}));if(!player.x){player.x=W/2;player.y=H*.72}draw()}
function draw(){const sec=sectors[state.sector]||sectors[0],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,sec.bg[0]);g.addColorStop(1,sec.bg[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawBackdrop(sec);drawStars();drawCores();drawPickups();drawEnemies();drawBullets();drawParticles();drawPlayer()}
function drawBackdrop(sec){if(sec.id==='earth'){planet(W*.84,H*.15,95,'#73dcff','#2469bd','#102d65')}if(sec.id==='moon'){planet(W*.84,H*.15,82,'#f1f1ed','#a6abb4','#555c67')}if(sec.id==='mars'){planet(W*.84,H*.16,98,'#ffc092','#bd5734','#512013')}if(sec.id==='hole'){ctx.save();ctx.translate(W*.82,H*.18);ctx.strokeStyle='#ffad5c';ctx.lineWidth=13;ctx.beginPath();ctx.ellipse(0,0,120,35,-.18,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#b36cff';ctx.lineWidth=7;ctx.beginPath();ctx.ellipse(0,0,145,43,-.18,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#000';ctx.beginPath();ctx.arc(0,0,48,0,Math.PI*2);ctx.fill();ctx.restore()}}
function planet(x,y,r,a,b,c){const g=ctx.createRadialGradient(x-r*.3,y-r*.3,4,x,y,r);g.addColorStop(0,a);g.addColorStop(.45,b);g.addColorStop(1,c);ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffffff22';ctx.lineWidth=6;ctx.stroke()}
function drawStars(){const fast=worldSpeed()>1;ctx.save();ctx.lineCap='round';state.stars.forEach(s=>{if(fast){ctx.strokeStyle='#d9f3ffaa';ctx.lineWidth=s.s;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x,s.y-22);ctx.stroke()}else{ctx.fillStyle='#ffffffaa';ctx.beginPath();ctx.arc(s.x,s.y,s.s,0,Math.PI*2);ctx.fill()}});ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);const sh=ships[state.ship];if(state.shieldT>0||player.inv>0){ctx.strokeStyle='#6fe9ffbb';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,35,42,0,0,Math.PI*2);ctx.stroke()}ctx.fillStyle=sh.id==='tank'?'#d7e5ff':'#f5fbff';ctx.strokeStyle='#4f6795';ctx.lineWidth=3;ctx.beginPath();if(sh.id==='sting'){ctx.moveTo(0,-31);ctx.lineTo(15,18);ctx.lineTo(29,28);ctx.lineTo(0,20);ctx.lineTo(-29,28);ctx.lineTo(-15,18)}else if(sh.id==='tank'){ctx.moveTo(0,-28);ctx.lineTo(24,-5);ctx.lineTo(28,24);ctx.lineTo(11,18);ctx.lineTo(0,31);ctx.lineTo(-11,18);ctx.lineTo(-28,24);ctx.lineTo(-24,-5)}else{ctx.moveTo(0,-32);ctx.lineTo(20,11);ctx.lineTo(29,23);ctx.lineTo(9,18);ctx.lineTo(0,31);ctx.lineTo(-9,18);ctx.lineTo(-29,23);ctx.lineTo(-20,11)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#4ecbff';ctx.beginPath();ctx.ellipse(0,-9,7,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=state.boost?'#fff06a':'#ff9a4e';ctx.beginPath();ctx.moveTo(-7,24);ctx.lineTo(0,48+(state.boost?20:0)+Math.random()*8);ctx.lineTo(7,24);ctx.closePath();ctx.fill();if(state.droneT>0){ctx.fillStyle='#8ffcff';ctx.beginPath();ctx.arc(31,-2,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}ctx.restore()}
function drawEnemies(){state.enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);const hp=e.hp/e.max;if(e.type==='scout'){ctx.fillStyle='#89f184';ctx.strokeStyle='#2b7440';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,18);ctx.lineTo(-20,-10);ctx.quadraticCurveTo(0,-27,20,-10);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#25304e';ctx.beginPath();ctx.ellipse(0,-8,9,6,0,0,Math.PI*2);ctx.fill()}else if(e.type==='zig'){ctx.fillStyle='#ff75c8';ctx.beginPath();ctx.ellipse(0,0,24,12,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9ae8ff';ctx.beginPath();ctx.ellipse(0,-8,11,8,0,Math.PI,Math.PI*2);ctx.fill()}else if(e.type==='gun'){ctx.fillStyle='#ffb54c';ctx.strokeStyle='#8e4c25';ctx.lineWidth=3;ctx.fillRect(-22,-14,44,28);ctx.strokeRect(-22,-14,44,28);ctx.fillStyle='#64382d';ctx.fillRect(-32,-4,10,8);ctx.fillRect(22,-4,10,8);ctx.fillStyle='#9df0ff';ctx.fillRect(-8,-7,16,10)}else{ctx.fillStyle='#9a74ff';ctx.beginPath();ctx.ellipse(0,0,30,14,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#bdf7ff';ctx.beginPath();ctx.ellipse(0,-10,15,11,0,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#fff06a';[-18,0,18].forEach(x=>{ctx.beginPath();ctx.arc(x,5,3,0,Math.PI*2);ctx.fill()})}if(e.max>1){ctx.fillStyle='#0008';ctx.fillRect(-22,-28,44,4);ctx.fillStyle='#69f0a8';ctx.fillRect(-22,-28,44*hp,4)}ctx.restore()})}
function drawBullets(){ctx.fillStyle='#fff069';ctx.shadowColor='#fff069';ctx.shadowBlur=8;state.bullets.forEach(b=>{ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()});ctx.shadowBlur=0;ctx.fillStyle='#ff6dbb';state.enemyBullets.forEach(b=>{ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()})}
function drawCores(){state.cores.forEach(c=>{ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.rot);ctx.strokeStyle='#69efff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-c.r);ctx.lineTo(c.r,0);ctx.lineTo(0,c.r);ctx.lineTo(-c.r,0);ctx.closePath();ctx.stroke();ctx.restore()})}
function drawPickups(){const icons={fuel:'⚡',repair:'🔧',rapid:'🔫',spread:'🔱',plasma:'🟣',shield:'🛡️',magnet:'🧲',drone:'🤖'};ctx.font='22px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';state.pickups.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.sin(p.rot)*.2);ctx.fillStyle='#111a3dcc';ctx.strokeStyle='#86eaff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillText(icons[p.type]||'★',0,1);ctx.restore()})}
function drawParticles(){const m={boom:'#ff944f',hit:'#fff06a',data:'#69efff',fuel:'#ffd55f',repair:'#62e5a6',rapid:'#55d7ff',spread:'#ff6cc4',plasma:'#a873ff',shield:'#62e5ff',magnet:'#ff75cb',drone:'#b9f8ff'};state.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=m[p.type]||'#fff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1}
function updateHud(){const sec=sectors[state.sector]||sectors[0];$('#hudSector').textContent=sec.short;$('#hudScore').textContent=state.score;$('#hudCombo').textContent='x'+state.combo;$('#hudFuel').textContent=Math.round(state.fuel)+'%';$('#fuelBar').style.width=Math.max(0,state.fuel)+'%';$('#hudHull').textContent=Math.round(state.hull)+'%';$('#hullBar').style.width=Math.max(0,state.hull)+'%';$('#hudKills').textContent=state.kills;$('#objectiveText').textContent=`Data ${state.data}/${sec.dataGoal} · Alien ${state.kills}/${sec.killGoal}`;const w=weapons[state.weapon];$('#weaponName').textContent=w.name;$('#weaponLevel').textContent='LV.'+state.weaponLevel;$('#weaponDesc').textContent=w.desc;$('#powerList').innerHTML=[['🛡️ Shield',state.shieldT],['🧲 Magnet',state.magnetT],['🤖 Drone',state.droneT],['🔫 Weapon',state.weaponT]].map(([n,t])=>`<div class="power-row"><span>${n}</span><b>${t>0?t.toFixed(1)+'s':'—'}</b></div>`).join('');$('#eventText').textContent=state.waveActive>0?'👾 Alien Wave กำลังโจมตี!':state.reverse?'⏬ Reverse thrust · โลกเคลื่อนช้าลง':state.boost?'⚡ Boost · ความเร็วสูงสุด':'บินต่อเนื่องและเตรียมรับ Wave ถัดไป'}
function bindHold(el,start,end){el.addEventListener('pointerdown',e=>{e.preventDefault();start();resetIdle()});['pointerup','pointercancel','pointerleave'].forEach(v=>el.addEventListener(v,end))}
function keyMove(k,v){if(k==='ArrowLeft'||k==='a'||k==='A')state.keys.left=v;if(k==='ArrowRight'||k==='d'||k==='D')state.keys.right=v;if(k==='ArrowUp'||k==='w'||k==='W')state.keys.up=v;if(k==='ArrowDown'||k==='s'||k==='S')state.keys.down=v}
function ensureAudio(){if(!state.audio){const A=window.AudioContext||window.webkitAudioContext;if(A)state.audio=new A()}if(state.audio?.state==='suspended')state.audio.resume().catch(()=>{})}
function sfx(type){if(!state.settings.sound||state.settings.volume<=0)return;ensureAudio();if(!state.audio)return;const a=state.audio,n=a.currentTime,g=a.createGain(),o=a.createOscillator(),v=state.settings.volume/100*.09,cfg={tap:[430,.05],count:[520,.08],go:[900,.18],launch:[180,.35],shoot:[780,.035],enemy:[250,.06],boom:[90,.17],hit:[110,.2],power:[620,.16],collect:[880,.1],wave:[300,.25],alarm:[160,.4],rescue:[560,.45],fail:[140,.25],clear:[420,.55]}[type]||[420,.08];o.type=['boom','hit','alarm'].includes(type)?'sawtooth':'sine';o.frequency.value=cfg[0];o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.0001,n+cfg[1]);o.start(n);o.stop(n+cfg[1]+.02)}
function updateSound(){$('#soundToggle').textContent=state.settings.sound?'🔊':'🔇'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function resetIdle(){clearTimeout(state.idle);state.idle=setTimeout(()=>{if(state.screen==='game'&&state.running){state.running=false;cancelAnimationFrame(state.raf)}show('home')},Math.max(15,state.settings.idle)*1000)}
function operatorRequest(){if(state.running){state.running=false;cancelAnimationFrame(state.raf);state._resume=true}else state._resume=false;$('#operatorPin').classList.remove('hidden');$('#pinInput').value='';$('#pinError').textContent='';setTimeout(()=>$('#pinInput').focus(),50)}
function operatorClose(){$('#operatorModal').classList.add('hidden');resumeIfNeeded()}function pinClose(){$('#operatorPin').classList.add('hidden');resumeIfNeeded()}function resumeIfNeeded(){if(state._resume&&state.screen==='game'&&!state.paused){state._resume=false;state.running=true;state.last=performance.now();state.raf=requestAnimationFrame(loop)}}
function bind(){
 $('#brandHome').addEventListener('click',()=>{state.running=false;cancelAnimationFrame(state.raf);show('home')});$('#startGame').addEventListener('click',()=>{state.ship=0;renderShips();show('setup')});$('#chooseShip').addEventListener('click',()=>{renderShips();show('setup')});$('#setupBack').addEventListener('click',()=>show('home'));$('#launchGame').addEventListener('click',setupRun);$('#briefStart').addEventListener('click',countdown);$('#endRun').addEventListener('click',()=>finishRun(false));$('#reportHome').addEventListener('click',()=>show('home'));$('#reportReplay').addEventListener('click',setupRun);
 bindHold($('#moveLeft'),()=>state.keys.left=true,()=>state.keys.left=false);bindHold($('#moveRight'),()=>state.keys.right=true,()=>state.keys.right=false);bindHold($('#moveUp'),()=>state.keys.up=true,()=>state.keys.up=false);bindHold($('#moveDown'),()=>state.keys.down=true,()=>state.keys.down=false);bindHold($('#shootBtn'),()=>{state.fire=true;ensureAudio()},()=>state.fire=false);bindHold($('#boostBtn'),()=>{state.boost=true;state.reverse=false},()=>state.boost=false);bindHold($('#reverseBtn'),()=>{state.reverse=true;state.boost=false},()=>state.reverse=false);
 arena.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','a','A','d','D','w','W','s','S'].includes(e.key)){keyMove(e.key,true);e.preventDefault()}if(e.code==='Space'){state.fire=true;e.preventDefault()}if(e.key==='Shift'){state.boost=true;e.preventDefault()}if(e.key==='Control'){state.reverse=true;e.preventDefault()}resetIdle()});arena.addEventListener('keyup',e=>{keyMove(e.key,false);if(e.code==='Space')state.fire=false;if(e.key==='Shift')state.boost=false;if(e.key==='Control')state.reverse=false});
 $('#soundToggle').addEventListener('click',()=>{state.settings.sound=!state.settings.sound;localStorage.setItem('cosmic.v4.settings',JSON.stringify(state.settings));updateSound();if(state.settings.sound)sfx('tap')});$('#operatorOpen').addEventListener('click',operatorRequest);$('#pinCancel').addEventListener('click',pinClose);$('[data-close-pin]').addEventListener('click',pinClose);$('#pinSubmit').addEventListener('click',()=>{const pin=localStorage.getItem('cosmic.v4.pin')||'2468';if($('#pinInput').value===pin){$('#operatorPin').classList.add('hidden');$('#operatorModal').classList.remove('hidden')}else{$('#pinError').textContent='PIN ไม่ถูกต้อง';sfx('fail')}});$('#pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#pinSubmit').click()});$('#operatorClose').addEventListener('click',operatorClose);$('[data-close-operator]').addEventListener('click',operatorClose);$('#volumeRange').addEventListener('input',e=>$('#volumeValue').textContent=e.target.value+'%');$('#idleRange').addEventListener('input',e=>$('#idleValue').textContent=e.target.value+'s');$('#operatorSave').addEventListener('click',()=>{state.settings.difficulty=$('#difficultySelect').value;state.settings.volume=+$('#volumeRange').value;state.settings.idle=+$('#idleRange').value;const p=$('#pinChange').value.trim();if(p&&!/^\d{4,8}$/.test(p))return toast('PIN ต้องเป็นเลข 4–8 หลัก');if(p)localStorage.setItem('cosmic.v4.pin',p);localStorage.setItem('cosmic.v4.settings',JSON.stringify(state.settings));$('#pinChange').value='';operatorClose();toast('บันทึก Operator Settings แล้ว')});$('#resetScores').addEventListener('click',()=>{localStorage.removeItem('cosmic.v4.leaders');renderLeaders();toast('ล้างคะแนนแล้ว')});document.addEventListener('pointerdown',resetIdle,{passive:true});window.addEventListener('resize',resize);new ResizeObserver(resize).observe(arena)
}
function init(){loadSettings();renderHome();renderShips();bind();resize();show('home');resetIdle()}init();
})();