(()=>{
  const $=s=>document.querySelector(s);
  const sectors=[['EARTH ORBIT','BLUE FRONT'],['LUNAR FRONT','MOON SECTOR'],['MARS RUN','RED DUST SECTOR'],['EVENT HORIZON','FINAL SECTOR']];
  let lastSector=null,lastBossKills=0,lastNear=0,critical=false,criticalBeep=0;
  let timers=[];
  const later=(fn,ms)=>{const t=setTimeout(fn,ms);timers.push(t);return t};
  function sound(kind){try{const cfg=JSON.parse(localStorage.getItem('cosmicExplorerV12Settings')||'{}');if(cfg.sound===false)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ac=window.__V123AC||(window.__V123AC=new AC());if(ac.state==='suspended')ac.resume().catch(()=>{});const n=ac.currentTime;const tone=(f,d,g=.025,type='sine',delay=0,end=null)=>{const o=ac.createOscillator(),v=ac.createGain();o.type=type;o.frequency.setValueAtTime(f,n+delay);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(30,end),n+delay+d);v.gain.setValueAtTime(.0001,n+delay);v.gain.exponentialRampToValueAtTime(g,n+delay+.015);v.gain.exponentialRampToValueAtTime(.0001,n+delay+d);o.connect(v);v.connect(ac.destination);o.start(n+delay);o.stop(n+delay+d+.03)};if(kind==='launch'){tone(90,.55,.035,'sawtooth',0,190);tone(220,.38,.018,'triangle',.16,440)}else if(kind==='sector'){tone(190,.22,.026,'triangle',0,420);tone(420,.32,.018,'sine',.1,720)}else if(kind==='near'){tone(760,.07,.015,'sine',0,980)}else if(kind==='critical'){tone(130,.12,.018,'square',0,90)}else if(kind==='finish'){tone(70,.6,.05,'sawtooth',0,42);tone(180,.28,.024,'triangle',.18,520)}}catch(_){}}
  function build(){if($('#v123Fx'))return;const fx=document.createElement('div');fx.id='v123Fx';fx.innerHTML=`<div class="v123-vignette"></div><div class="v123-critical">HULL CRITICAL</div><div class="v123-launch"><div class="v123-streaks"></div><div class="v123-card" id="v123LaunchCard"><div class="v123-ey">LAUNCH SEQUENCE</div><div class="v123-title">MISSION START</div><div class="v123-sub">AUTO FIRE ONLINE · DRAG TO FLY</div></div></div><div class="v123-warp"><div class="v123-streaks"></div><div class="v123-card" id="v123SectorCard"><div class="v123-ey" id="v123SectorEy">NOW ENTERING</div><div class="v123-title" id="v123SectorTitle">EARTH ORBIT</div><div class="v123-sub" id="v123SectorSub">BLUE FRONT</div></div></div><div class="v123-near">NEAR MISS</div><div class="v123-finisher"><div class="v123-card" id="v123FinishCard"><div class="v123-ey">TARGET NEUTRALIZED</div><div class="v123-title" id="v123FinishTitle">CORE DESTROYED</div><div class="v123-sub">SECTOR SECURED</div></div></div><div class="v123-streak" id="v123Streak">SECTOR STREAK ×1</div>`;document.body.appendChild(fx);document.querySelectorAll('#v123Fx .v123-streaks').forEach(box=>{for(let i=0;i<18;i++){const s=document.createElement('i');s.style.setProperty('--r',(i*20)+'deg');s.style.marginLeft=((i%5)-2)*14+'px';s.style.animationDelay=(-i*.037)+'s';box.appendChild(s);}})}
  function showLaunch(){build();const l=$('#v123Fx .v123-launch'),c=$('#v123LaunchCard');l.classList.add('on');c.classList.add('on');sound('launch');later(()=>c.classList.remove('on'),1250);later(()=>l.classList.remove('on'),1600)}
  function showSector(sec){build();const d=sectors[sec]||sectors[0],w=$('#v123Fx .v123-warp'),c=$('#v123SectorCard');$('#v123SectorTitle').textContent=d[0];$('#v123SectorSub').textContent=d[1];w.classList.add('on');c.classList.add('on');sound('sector');later(()=>c.classList.remove('on'),950);later(()=>w.classList.remove('on'),1250)}
  function showNear(){const n=$('#v123Fx .v123-near');if(!n)return;n.classList.remove('on');void n.offsetWidth;n.classList.add('on');sound('near')}
  function showFinish(kills){const f=$('#v123Fx .v123-finisher'),c=$('#v123FinishCard'),st=$('#v123Streak');if(!f)return;$('#v123FinishTitle').textContent=kills>=4?'FINAL CORE DESTROYED':'CORE DESTROYED';f.classList.add('on');c.classList.add('on');st.textContent='SECTOR STREAK ×'+kills;st.classList.remove('on');void st.offsetWidth;st.classList.add('on');sound('finish');later(()=>c.classList.remove('on'),900);later(()=>f.classList.remove('on'),1150)}
  function tick(){build();const api=window.__COSMIC_V12,st=api?.status?.();if(st){if(st.playing){if(lastSector===null)lastSector=st.sector;else if(st.sector!==lastSector){lastSector=st.sector;showSector(st.sector)}if((st.bossKills||0)>lastBossKills){lastBossKills=st.bossKills||0;showFinish(lastBossKills)}const ratio=st.maxHp>0?st.hp/st.maxHp:1;if(!critical&&ratio>0&&ratio<.28){critical=true;$('#v123Fx').classList.add('lowhp');criticalBeep=0}else if(critical&&ratio>.36){critical=false;$('#v123Fx').classList.remove('lowhp')}if(critical&&performance.now()-criticalBeep>1250){criticalBeep=performance.now();sound('critical')}if(st.nearMiss&&performance.now()-lastNear>850&&!st.paused){lastNear=performance.now();showNear()}}else{$('#v123Fx')?.classList.remove('lowhp');critical=false;lastSector=null;lastBossKills=0}}requestAnimationFrame(tick)}
  window.addEventListener('cosmic:v12-start',()=>{lastSector=null;lastBossKills=0;showLaunch()});window.addEventListener('cosmic:report',()=>{$('#v123Fx')?.classList.remove('lowhp');critical=false});
  function register(){if('serviceWorker'in navigator&&location.protocol==='https:')setTimeout(()=>navigator.serviceWorker.register('/sw-v123.js?v=123',{scope:'/'}).catch(()=>{}),500)}
  const ready=()=>{build();const tag=$('.v11tag');if(tag)tag.textContent='ARCADE SPACE MISSION · V12.3 CINEMATIC GAME FEEL';register();requestAnimationFrame(tick)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();